[package]
authors = ["Maiddog <maiddogsrl@gmail.com>", "BeaconBrigade <beaconbrigade@gmail.com>"]
description = "A Rust library for offline PPI recording with Polar Verity Sense"
documentation = "https://docs.rs/arctic"
homepage = "https://github.com/Roughsketch/arctic"
keywords = ["polar", "bluetooth", "heartrate", "ppi"]
license = "MIT"
name = "arctic"
readme = "README.md"
repository = "https://github.com/Roughsketch/arctic.git"
version = "1.0.0"
edition = "2021"

[lib]
name = "arctic"
path = "src/lib.rs"

[dependencies]
btleplug = "0.11"
futures = "0.3"
tokio = { version = "1.10.0", features = ["macros", "rt", "rt-multi-thread", "time"] }
tokio-stream = { version = "0.1", features = ["sync"] }
uuid = "1"

[dev-dependencies]
tokio-test = "0.4"
